lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

github: [metadata]

collections:
  projects:
    output: true

title: Tristan Meyrowski | Web Developer 
description: >
  I'm a Freelance Web Developer based in Lille, France. Take a look at my resume and my works. 
#source: "https://github.com/TMeyrowski/tristanmeyrowski.com.git"
source: "/Users/tmeyrowski/Documents/workspace/tristanmeyrowski.com/"

readme_index:
  enabled:          false
  remove_originals: false
  with_frontmatter: false