lsi: false
safe: true
source: "https://github.com/TMeyrowski/tristanmeyrowski.com.git"
#source: "/Users/tmeyrowski/Documents/workspace/tristanmeyrowski.com/"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge